# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Izmen_category1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(386, 253)
        self.pushButton1_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton1_2.setGeometry(QtCore.QRect(110, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton1_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton1_3.setGeometry(QtCore.QRect(110, 200, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton1_3.setFont(font)
        self.pushButton1_3.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 271, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Fon = QtWidgets.QLabel(Dialog)
        self.Fon.setGeometry(QtCore.QRect(0, -10, 401, 271))
        self.Fon.setText("")
        self.Fon.setPixmap(QtGui.QPixmap("C:/Users/Кристина/Downloads/Frame 7.png"))
        self.Fon.setObjectName("Fon")
        self.Fon.raise_()
        self.pushButton1_2.raise_()
        self.pushButton1_3.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton1_2.setText(_translate("Dialog", "Сохранить изменения"))
        self.pushButton1_3.setText(_translate("Dialog", "Удалить категорию"))
        self.label.setText(_translate("Dialog", "Изменить категорию"))
        self.label_2.setText(_translate("Dialog", "Название"))
