# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O9.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1423, 721)
        self.polosa2 = QtWidgets.QLabel(Form)
        self.polosa2.setGeometry(QtCore.QRect(-30, 100, 1621, 20))
        self.polosa2.setObjectName("polosa2")
        self.polosa2_2 = QtWidgets.QLabel(Form)
        self.polosa2_2.setGeometry(QtCore.QRect(-20, 180, 1621, 20))
        self.polosa2_2.setObjectName("polosa2_2")
        self.pushButtonGlavnaya4 = QtWidgets.QPushButton(Form)
        self.pushButtonGlavnaya4.setGeometry(QtCore.QRect(60, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonGlavnaya4.setFont(font)
        self.pushButtonGlavnaya4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonGlavnaya4.setObjectName("pushButtonGlavnaya4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonOtchet4 = QtWidgets.QPushButton(Form)
        self.pushButtonOtchet4.setGeometry(QtCore.QRect(1100, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonOtchet4.setFont(font)
        self.pushButtonOtchet4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonOtchet4.setObjectName("pushButtonOtchet4")
        self.pushSale4 = QtWidgets.QPushButton(Form)
        self.pushSale4.setGeometry(QtCore.QRect(740, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushSale4.setFont(font)
        self.pushSale4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushSale4.setObjectName("pushSale4")
        self.pushButton1_3 = QtWidgets.QPushButton(Form)
        self.pushButton1_3.setGeometry(QtCore.QRect(260, 140, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton1_3.setFont(font)
        self.pushButton1_3.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.pushButtonSupplier4 = QtWidgets.QPushButton(Form)
        self.pushButtonSupplier4.setGeometry(QtCore.QRect(410, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonSupplier4.setFont(font)
        self.pushButtonSupplier4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonSupplier4.setObjectName("pushButtonSupplier4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-4, -8, 1441, 911))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Кристина/Downloads/fonn.png"))
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(100, 240, 1191, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2.raise_()
        self.polosa2.raise_()
        self.polosa2_2.raise_()
        self.pushButtonGlavnaya4.raise_()
        self.label.raise_()
        self.pushButtonOtchet4.raise_()
        self.pushSale4.raise_()
        self.pushButton1_3.raise_()
        self.pushButtonSupplier4.raise_()
        self.graphicsView.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.polosa2.setText(_translate("Form", "___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"))
        self.polosa2_2.setText(_translate("Form", "___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"))
        self.pushButtonGlavnaya4.setText(_translate("Form", "Товары"))
        self.label.setText(_translate("Form", "Отчеты"))
        self.pushButtonOtchet4.setText(_translate("Form", "Отчеты"))
        self.pushSale4.setText(_translate("Form", "Продажи"))
        self.pushButton1_3.setText(_translate("Form", "Сформировать"))
        self.pushButtonSupplier4.setText(_translate("Form", "Поставщики"))
